---
{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: metricbeat
  labels:
    k8s-app: metricbeat
spec:
  selector:
    matchLabels:
      k8s-app: metricbeat
  template:
    metadata:
      labels:
        k8s-app: metricbeat
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: metricbeat
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
{{- if .Values.global -}}
  {{- if .Values.global.sharedTokens }}
    {{- if .Values.global.sharedTokens.metricbeat }}
      {{- if .Values.es.autodiscovery }}
      initContainers:
        - name: wait-for-shared-tokens
          image: {{ .Values.initImage }}
          imagePullPolicy: {{ .Values.initImagePullPolicy }}
          command:
          - kubectl
          - wait
          - "--for=condition=Complete"
          - "job/{{ .Release.Name }}-create-shared-tokens"
          - "-n"
          - {{ .Release.Namespace }}
          - "--timeout=1500s"
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end  }}
      containers:
      - name: metricbeat
        image: {{ .Values.image }}
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
      {{- if .Values.es.autodiscovery }}
        {{- if .Values.es.tls }}
          value: "https://{{ .Release.Name }}-humio-core-es.{{ .Release.Namespace }}"
        {{- else }}
          value: "{{ .Release.Name }}-humio-core-es.{{ .Release.Namespace }}"
        {{- end }}
      {{- else }}
        {{- if .Values.es.tls }}
          value: "https://{{ .Values.humioHostname }}"
        {{- else }}
          value: "{{ .Values.humioHostname }}"
        {{- end }}
      {{- end }}
        - name: ELASTICSEARCH_PORT
          value: {{ default "9200" .Values.es.port | quote }}
        - name: ELASTICSEARCH_USERNAME
          value: none
        {{- if .Values.token }}
        - name: ELASTICSEARCH_PASSWORD
          value: {{ .Values.token }}
        {{- else }}
          {{- if .Values.global -}}
            {{- if .Values.global.sharedTokens }}
              {{- if .Values.global.sharedTokens.metricbeat }}
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: metricbeat-shared-token
              key: token
              {{- end -}}
            {{- end -}}
          {{- end  }}
        {{- end  }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/metricbeat.yml
          readOnly: true
          subPath: metricbeat.yml
        - name: modules
          mountPath: /usr/share/metricbeat/modules.d
          readOnly: true
      securityContext:
        fsGroup: 1000
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: metricbeat-deployment-config
      - name: modules
        configMap:
          defaultMode: 0600
          name: metricbeat-deployment-modules
